version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Code/scholar
hooks:
  BeforeInstall:
    - location: scripts/ls
      timeout: 300 
      runas: root 
  AfterInstall:
    - location: scripts/ls
      timeout: 300 
      runas: root 
  ApplicationStart:
    - location: pm2 start hello
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ls 
      timeout: 300 
      runas: root 
