--- 
files: 
  - 
    destination: /home/ec2-user/Code/scholar
    source: /
hooks: 
  AfterInstall: 
    - 
      location: scripts/install-node-stuff.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart: 
    - 
      location: scripts/start-app.sh
      runas: root
      timeout: 300
  ApplicationStop: 
    - 
      location: scripts/stop-app.sh
      runas: root
      timeout: 300
  BeforeInstall: 
    - 
      location: scripts/remove_all_code.sh
      runas: root
      timeout: 300
os: linux
permissions: 
  - 
    group: ec2-user
    object: /home/ec2-user/Code/scholar
    owner: ec2-user
    type: directory
version: 0.0
