version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Code/scholar
hooks:
  BeforeInstall:
    - location: scripts/remove_all_code
      timeout: 300 
      runas: root 
  AfterInstall:
    - location: scripts/install-node-stuff.sh
      timeout: 300 
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/ls 
      timeout: 300 
      runas: root 
