version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Code/scholar
permissions:
  - object: /home/ec2-user/Code/scholar
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/remove_all_code
      timeout: 300 
      runas: root 
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-app.sh 
      timeout: 300 
      runas: root 
