version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
        npm install
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Starting tests on `date`
      - echo npm test >> test.results.mocha
      - echo Finished  tests on `date`
artifacts:
  files:
    - '**/*'
