version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
        npm install
  build:
    commands:
      - echo Build started on `date`
  post_build:
    run-as: ec2-user
    commands:
      - echo Build completed on `date`
      - echo Starting tests on `date`
      - npm test >> ~/Code/scholar/test.results.mocha
      - echo Finished  tests on `date`
artifacts:
  files:
    - '**/*'
