version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
        npm install
  build:
    commands:
      - echo Build started on `date`
      - /home/ec2-user/Code/scholar/scripts/test_app_with_mocha
  post_build:
    commands:
      - echo Nothing to do postbuild
artifacts:
  files:
    - '**/*'
