version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - /bin/bash scripts/test_app_with_mocha
  post_build:
    commands:
      - echo Nothing to do postbuild
artifacts:
  files:
    - '**/*'
