version: 0.2

phases:
  install:
    commands:
      - echo installing mongo
      - yum install -y mongodb-org
      - service mongod start && su - ec2-user -c "/home/ec2-user/Code/scholar/scripts/import-db.sh"
      - echo installing npm
      - npm install
      - echo installing mocha
      - npm -g install mocha
      - npm install chai --save-dev
      - npm install chai-http --save-dev
      - npm -g install pm2
      - npm install pug --save-dev
      - npm install express --save-dev
      - npm install should --save-dev
  pre_build:
    commands:
      - echo not much more to do....
  build:
    commands:
      - echo Build started on `date`
      - pm2 start node/hello.js &&  /bin/bash scripts/test_app_with_mocha
  post_build:
    commands:
      - echo Nothing to do postbuild
artifacts:
  files:
    - '**/*'
