version: 0.2

phases:
  install:
    commands:
      - echo installing mocha
      - npm -g install mocha
      - npm -g install chai
      - npm -g install chai-http
      - npm -g install pm2
      - npm -g install pug
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - /bin/bash scripts/test_app_with_mocha
  post_build:
    commands:
      - echo Nothing to do postbuild
artifacts:
  files:
    - '**/*'
