#!/bin/sh
OUTFILE="test.results.mocha"
/usr/bin/touch $OUTFILE
echo "TEST SCRIPT starting mocha tests" > $OUTFILE
/bin/date >> $OUTFILE
cd node && echo "TEST SCRIPT changed dir" >> $OUTFILE
# . /home/ec2-user/.nvm/nvm.sh && echo "TEST SCRIPT included nvm.sh " >> $OUTFILE
npm test >> $OUTFILE && exit 0
