#!/bin/sh
OUTFILE = "~/Code/scholar/test.results.mocha"
echo "starting mocha tests" > $OUTFILE
cd /home/ec2-user/Code/scholar/node && echo "changed dir" >> $OUTFILE
. /home/ec2-user/.nvm/nvm.sh && echo "included nvm.sh " >> $OUTFILE
mocha tests/ >> $OUTFILE
