#!/bin/sh
OUTFILE="/home/ec2-user/Code/scholar/test.results.mocha"
touch $OUTFILE
echo "TEST SCRIPT starting mocha tests" > $OUTFILE
date >> $OUTFILE
cd /home/ec2-user/Code/scholar/node && echo "TEST SCRIPT changed dir" >> $OUTFILE
. /home/ec2-user/.nvm/nvm.sh && echo "TEST SCRIPT included nvm.sh " >> $OUTFILE
mocha tests/ >> $OUTFILE
